site_name: QwikGeo Docs
site_url: https://docs.qwikgeo.com/
site_description: Tech docs for QwikGeo
site_author: Michael Keller

repo_url: https://github.com/mkeller3/QwikGeo
repo_name: QwikGeo
edit_uri: blob/main/docs/

extra_css:
  - stylesheets/extra.css

theme:
  name: material

markdown_extensions:
    - toc:
        permalink: 
    - attr_list
    - def_list
    - pymdownx.snippets

dev_addr: '127.0.0.1:5000'