site_name: FastGeoportal Tech Docs
site_url: https://mkeller3.github.io/FastGeoportal/
site_description: Tech docs for FastGeoportal
site_author: MkDocs Team

repo_url: https://github.com/mkeller3/FastGeoportal
repo_name: FastGeoportal
edit_uri: blob/main/docs/

extra_css:
  - stylesheets/extra.css

theme:
  name: material

markdown_extensions:
    - toc:
        permalink: 
    - attr_list
    - def_list
    - pymdownx.snippets

dev_addr: '127.0.0.1:5000'